version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=instagrao
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    networks:
      - app


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@cwi.com.br
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 9000:80
    networks:
      - app

  app:
    container_name: instagrao
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/instagrao
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - postgres


networks:
  app:

volumes:
  postgres-data:
  pgadmin-data: